name: getBranchName
on: [pull_request, push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV"
        id: extract_branch

      # extract branch name on pull request
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF} >> $GITHUB_ENV"

      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' env.$BRANCH_NAME
