name: github-actions
on: [push]
jobs:
  check-header:
    name: Check Header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -V
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: check-header
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: java -version
      - run: pwd && ls -la
  code-scan:
    name: Code Scan
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - run: java -version
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: java -version
      - run: pwd && ls -la
  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: java -version
      - run: pwd && ls -la
  
