name: github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: java -version
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5'
      - run: python -V
